/*
 * Copyright (C) 2004 TES Electronic Solutions GmbH,
 * All Rights Reserved.
 * This source code and any compilation or derivative thereof is the
 * proprietary information of TES Electronic Solutions GmbH
 * and is confidential in nature.
 * Under no circumstances is this software to be exposed to or placed
 * under an Open Source License of any type without the expressed
 * written permission of TES Electronic Solutions GmbH
 *
 *############################################################
*/
/*******************************************************************************
*   PROJECT:        Guiliani
********************************************************************************
*
*    MODULE:        GUIConfig.cpp
*
*    Archive:       $URL: https://10.25.129.51:3690/svn/Guiliani/branches/Releases/2.2/Share/GUIConfig.cpp $
*
*    Date created:  2014
*
*
*
*    Author:        CEU
*
********************************************************************************
*   MODIFICATIONS
********************************************************************************
*    ID
*    --------------------------------------------------------------------------
*    $Id: GUIConfig.cpp 3796 2014-03-03 10:52:09Z christoph.loew $
*
*******************************************************************************/

#include "eC_String.h"
#include "GUIBehaviourResource.h"
#include "GUICommandResource.h"
#include "GUIControlResource.h"
#include "GUIFontResource.h"
#include "GUIImageResource.h"
#include "GUIGeneralResource.h"
#include "GUILayouterResource.h"
#include "GUILocaleResource.h"
#include "GUIObjectHandleResource.h"
#include "GUIPropertyResource.h"
#include "GUISoundResource.h"
#include "GUITextResource.h"
#include "GUIDataPoolResource.h"

/*
##################################################################################
                    DO NOT EDIT THIS FILE !!!!
##################################################################################
*/

// -----------------------------------------------------------------------------------------
// global properties

const eC_UInt cuiNOFGlobalProperties = MAP_PROPID_TO_ARRAY(NOF_PROPERTIES);

// -----------------------------------------------------------------------------------------
//  font resources

const eC_UInt cuiNOFFontResources = MAP_FNTID_TO_ARRAY(NOF_FONTRESOURCES);

// -----------------------------------------------------------------------------------------
//  image resources

const eC_UInt cuiNOFImageResources = MAP_IMGID_TO_ARRAY(NOF_IMAGERESOURCES);

// -----------------------------------------------------------------------------------------
//  text resources

const eC_UInt cuiNOFTextResources = MAP_TEXTID_TO_ARRAY(NOF_TEXTRESOURCES);

// -----------------------------------------------------------------------------------------
// sound resources

const eC_UInt cuiNOFSoundResources = MAP_SNDID_TO_ARRAY(NOF_SOUNDRESOURCES);

// -----------------------------------------------------------------------------------------
//  Object Handles

const eC_UInt cuiNOFObjectHandles = MAP_OBJID_TO_ARRAY(NOF_OBJECTHANDLES);

// -----------------------------------------------------------------------------------------
//  locale Handles

const eC_UInt cuiNOFLocaleHandles = MAP_PROPID_TO_ARRAY(NOF_LOCALEHANDLES);

// -----------------------------------------------------------------------------------------
//  command Handles

const eC_UInt cuiNOFCommandClasses = MAP_PROPID_TO_ARRAY(NOF_COMMANDCLASSES);

// -----------------------------------------------------------------------------------------
//  general resource file Handles

const eC_UInt cuiNOFGeneralResources = MAP_RESID_TO_ARRAY(NOF_GENERALRESOURCES);

// -----------------------------------------------------------------------------------------
//  DataPool resource Handles

const eC_UInt cuiNOFDataPoolResources = MAP_DATAPOOLID_TO_ARRAY(NOF_DATAPOOLRESOURCES);
