// Generated by GSE. Edit at your own risk.

#if !defined(USER_FONT_RESOURCE_H)
#define USER_FONT_RESOURCE_H

#define USER_FONT_TABLE            \
ENTRY(LAST_GENERATED_FONT_ID, "",0 ,0 , true)

#endif // USER_FONT_RESOURCE_H
