// Generated by GSE. Edit at your own risk.

#if !defined(USER_PROPERTY_RESOURCE_H)
#define USER_PROPERTY_RESOURCE_H

#define USER_PROPERTY_TABLE            \
ENTRY(LAST_GENERATED_PROPERTY_ID, 0, CGUIValue::EC_INT)

#endif // USER_PROPERTY_RESOURCE_H
