// Generated by GSE. Edit at your own risk.

#if !defined(USER_SOUND_RESOURCE_H)
#define USER_SOUND_RESOURCE_H

#define USER_SOUND_TABLE            \
ENTRY(LAST_GENERATED_SOUND_ID, "", true)

#endif // USER_SOUND_RESOURCE_H
