// Generated by GSE. Edit at your own risk.

#if !defined(USER_IMAGE_RESOURCE_H)
#define USER_IMAGE_RESOURCE_H

#define USER_IMAGE_TABLE            \
ENTRY(LAST_GENERATED_IMAGE_ID, "", true)

#endif // USER_IMAGE_RESOURCE_H
