#if !defined(USER_CONTROL_RESOURCE_H)
#define USER_CONTROL_RESOURCE_H

/*
This file includes a header which has been generated by GSE.
Add StreamRuntime IDs _before_ the ENTRY_ENUM(CUSTOM_XXX_START_TAG = 10000).
*/

#define STREAMRUNTIME_CONTROL_TABLE            \
ENTRY_ENUM(CUSTOM_CONTROLS_START_TAG = 10000) 

#include "CustomControlResource.h"

#define USER_CONTROL_TABLE            \
STREAMRUNTIME_CONTROL_TABLE \
CUSTOM_CONTROL_TABLE 


#endif // USER_CONTROL_RESOURCE_H
