// Generated by GSE. Edit at your own risk.

#if !defined(USER_GENERAL_RESOURCE_H)
#define USER_GENERAL_RESOURCE_H

#define USER_GENERAL_RESOURCES_TABLE            \
ENTRY(LAST_GENERATED_GENERAL_ID, "", true)

#endif // USER_GENERAL_RESOURCE_H
