// Generated by GSE. Edit at your own risk.

#if !defined(USER_TEXT_RESOURCE_H)
#define USER_TEXT_RESOURCE_H

#define USER_TEXT_TABLE            \
ENTRY(LAST_GENERATED_TEXT_ID)

#endif // USER_TEXT_RESOURCE_H
