#if !defined(USER_BEHAVIOUR_RESOURCE_H)
#define USER_BEHAVIOUR_RESOURCE_H

/*
This file includes a header which has been generated by GSE.
Add StreamRuntime IDs _before_ the ENTRY_ENUM(CUSTOM_XXX_START_TAG = 10000).
*/

#define STREAMRUNTIME_BEHAVIOUR_TABLE            \
ENTRY_ENUM(CUSTOM_BEHAVIOURS_START_TAG = 10000) 

#include "CustomBehaviourResource.h"

#define USER_BEHAVIOUR_TABLE            \
STREAMRUNTIME_BEHAVIOUR_TABLE \
CUSTOM_BEHAVIOUR_TABLE 


#endif // USER_BEHAVIOUR_RESOURCE_H
