#if !defined(USER_COMMAND_RESOURCE_H)
#define USER_COMMAND_RESOURCE_H

/*
This file includes a header which has been generated by GSE.
Add StreamRuntime IDs _before_ the ENTRY_ENUM(CUSTOM_XXX_START_TAG = 10000).
*/

#define STREAMRUNTIME_COMMAND_TABLE            \
ENTRY_ENUM(CUSTOM_COMMANDS_START_TAG = 10000) 

#include "CustomCommandResource.h"

#define USER_COMMAND_TABLE            \
STREAMRUNTIME_COMMAND_TABLE \
CUSTOM_COMMAND_TABLE 


#endif // USER_COMMAND_RESOURCE_H
