#if !defined(USER_LAYOUTER_RESOURCE_H)
#define USER_LAYOUTER_RESOURCE_H

/*
This file includes a header which has been generated by GSE.
Add StreamRuntime IDs _before_ the ENTRY_ENUM(CUSTOM_XXX_START_TAG = 10000).
*/

#define STREAMRUNTIME_LAYOUTER_TABLE            \
ENTRY_ENUM(CUSTOM_LAYOUTERS_START_TAG = 10000) 

#include "CustomLayouterResource.h"

#define USER_LAYOUTER_TABLE            \
STREAMRUNTIME_LAYOUTER_TABLE \
CUSTOM_LAYOUTER_TABLE 


#endif // USER_LAYOUTER_RESOURCE_H
