/*
* Copyright (C) TES Electronic Solutions GmbH,
* All Rights Reserved.
* Contact: info@guiliani.de
*
* This file is part of the Guiliani HMI framework
* for the development of graphical user interfaces on embedded systems.
*/

#ifndef GUI_ANIMATION_RESOURCE__H_
#define GUI_ANIMATION_RESOURCE__H_
#include <limits.h>

/// @file GUIAnimationResource.h @ref page_helpermacros
// 
// DO NOT EDIT THIS FILE!!! Add your own IDS within UserXXXResource.h files!
// DO NOT EDIT THIS FILE!!! Add your own IDS within UserXXXResource.h files!
// DO NOT EDIT THIS FILE!!! Add your own IDS within UserXXXResource.h files!
//
// -----------------------------------------------------------------------------------------
///  AnimationIDs
//Add Guiliani-AnimationType_t here (with negative IDs, DUMMY_ANIMATION has to stay 0)
#define ANIMATION_TABLE            \
ENTRY(ANIMATION_STDGUIOBJECT, CGUIAnimationStdGUIObject) \
ENTRY(ANIMATION_BLINKING, CGUIAnimationBlinking) \
ENTRY(ANIMATION_MOVE_IN_OUT, CGUIAnimationMoveInOut) \
ENTRY(ANIMATION_SIZE, CGUIAnimationSize) \
ENTRY(ANIMATION_MOVE, CGUIAnimationMove)

#ifndef GUILIANI_GUILIANILIB
    #include "UserAnimationResource.h"
#endif

/// List of animation resource ids.
enum AnimationType_t
{
     ANIMATION_START_TAG=-6,
#define ENTRY_ENUM(a) a, ///< \ref page_helpermacros
#define ENTRY(anim_id, anim_classname) anim_id,  ///< \ref page_helpermacros
     ANIMATION_TABLE
     DUMMY_ANIMATION=0,
#ifndef GUILIANI_GUILIANILIB
    USER_ANIMATION_TABLE
#endif
#undef ENTRY
#undef ENTRY_ENUM

     GUILIANI_INTERNAL_ANIMATION = INT_MAX // Do not touch this. Required for ensuring consistent enum type size across libraries.
};

#endif
