/*
* Copyright (C) TES Electronic Solutions GmbH,
* All Rights Reserved.
* Contact: info@guiliani.de
*
* This file is part of the Guiliani HMI framework
* for the development of graphical user interfaces on embedded systems.
*/

#ifndef GUI_BEHAVIOUR_RESOURCE__H_
#define GUI_BEHAVIOUR_RESOURCE__H_
#include <limits.h>

/// @file GUIBehaviourResource.h @ref page_helpermacros
// 
// DO NOT EDIT THIS FILE!!! Add your own IDS within UserXXXResource.h files!
// DO NOT EDIT THIS FILE!!! Add your own IDS within UserXXXResource.h files!
// DO NOT EDIT THIS FILE!!! Add your own IDS within UserXXXResource.h files!
//

// -----------------------------------------------------------------------------------------
///  BehaviourClassIDs

//Add Guiliani-BehaviourClassIDs here (with negative IDs, DUMMY_BEHAVIOUR has to stay 0, see BEHAVIOUR_START_TAG below)

#define BEHAVIOUR_TABLE            \
ENTRY(BEHAVIOUR_KEYBOARD, CGUIKeyboardBehaviour) \
ENTRY(BEHAVIOUR_OBJECT_STATE, CGUIObjectStateBehaviour) \
ENTRY(BEHAVIOUR_COMPOSITE, CGUICompositeBehaviour) \
ENTRY(BEHAVIOUR_HOTKEY, CGUIHotkeysBehaviour) \
ENTRY(BEHAVIOUR_SINGLE_CMD, CGUISingleCmdBehaviour) \
ENTRY(BEHAVIOUR_MULTI_CMD, CGUIMultiCmdBehaviour)

#ifndef GUILIANI_GUILIANILIB
    #include "UserBehaviourResource.h"
#endif

/// List of behaviour class ids.
enum BehaviourClassID_t 
{
    BEHAVIOUR_START_TAG=-7,

#define ENTRY_ENUM(a) a, ///< \ref page_helpermacros
#define ENTRY(beh_id, beh_classname) beh_id, ///< \ref page_helpermacros
    BEHAVIOUR_TABLE

    DUMMY_BEHAVIOUR=0,
#ifndef GUILIANI_GUILIANILIB
    USER_BEHAVIOUR_TABLE
#endif
#undef ENTRY
#undef ENTRY_ENUM

    GUILIANI_INTERNAL_BHV = INT_MAX // Do not touch this. Required for ensuring consistent enum type size across libraries.
};

#endif
